name: check and create pull requests to update external dependency versions
on:
  schedule:
    - cron: '23 8 * * *'

permissions:
  pull-requests: write

jobs:
  check-update-versions:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: npm ci

      - run: npm run rddepman
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
